// <auto-generated />
using Homework67.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Homework67.Migrations
{
    [DbContext(typeof(CountryContext))]
    [Migration("20211015095015_DataSeed")]
    partial class DataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Homework67.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "USA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "England"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 5,
                            Name = "KG"
                        },
                        new
                        {
                            Id = 6,
                            Name = "KZ"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Spain"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
